version: "3"
services:
  client:
    build:
      context: ./client
    ports:
      - "3000:3000"
    depends_on:
      - server

  server:
    build:
      context: ./server
    ports:
      - "5000:5000"
    environment:
      - MONGODB_URI=mongodb://mongo:27018/Mission-Ready-M5
      - MONGODB_SEEDING="mongodb://mongo:27018"
    depends_on:
      - mongo
    command: ["sh", "-c", "npm run seed && node server.js"] # Add this line to run the seeding during startup
  mongo:
    image: mongo
    restart: always
    expose:
      - "27018"
    ports:
      - "27018:27018"

    volumes:
      - mongo-data:/data/db # Add this line to define a volume for MongoDB data

volumes:
  mongo-data: # Define the volume for MongoDB data

# docker-compose build        for major changes on Dockerfile / docker-compose.yml
#docker-compose up --build     for minor day to day changes
# docker-compose up

