name: CI Workflow

on:
  push:
    branches:
      - vatthana

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Build and Test Client
        run: |
          cd client
          # Assuming your client project uses a package manager like npm or yarn
          npm install 
          npm run build 
          npm test
          - name: Zip artifact for deployment
          run: zip release.zip ./* -r

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: node-app
          path: release.zip

      - name: Archive code coverage results
        uses: actions/upload-artifact@v3
        with:
          name: code-coverage-report
          path: coverage/*

      - name: Build Server
        run: |
          cd server
          # Assuming your server project uses a package manager like npm or yarn
          npm install
